'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.296
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Espanol
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("UI.Espanol", GetType(Espanol).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Bitacora.
        '''</summary>
        Friend Shared ReadOnly Property BitacoraToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("BitacoraToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reportes Bitacora.
        '''</summary>
        Friend Shared ReadOnly Property BitacoraToolStripMenuItem1() As String
            Get
                Return ResourceManager.GetString("BitacoraToolStripMenuItem1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Alta.
        '''</summary>
        Friend Shared ReadOnly Property btnalta() As String
            Get
                Return ResourceManager.GetString("btnalta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Baja.
        '''</summary>
        Friend Shared ReadOnly Property btnBaja() As String
            Get
                Return ResourceManager.GetString("btnBaja", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Alta.
        '''</summary>
        Friend Shared ReadOnly Property btnClieAlta() As String
            Get
                Return ResourceManager.GetString("btnClieAlta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Baja.
        '''</summary>
        Friend Shared ReadOnly Property btnCliebaja() As String
            Get
                Return ResourceManager.GetString("btnCliebaja", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Listar.
        '''</summary>
        Friend Shared ReadOnly Property btnClieList() As String
            Get
                Return ResourceManager.GetString("btnClieList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modificar.
        '''</summary>
        Friend Shared ReadOnly Property btnClieMod() As String
            Get
                Return ResourceManager.GetString("btnClieMod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Listar.
        '''</summary>
        Friend Shared ReadOnly Property btnListar() As String
            Get
                Return ResourceManager.GetString("btnListar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Listar Todos los Eventos.
        '''</summary>
        Friend Shared ReadOnly Property btnListarTodos() As String
            Get
                Return ResourceManager.GetString("btnListarTodos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modificar.
        '''</summary>
        Friend Shared ReadOnly Property btnModificar() As String
            Get
                Return ResourceManager.GetString("btnModificar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cambiar Password.
        '''</summary>
        Friend Shared ReadOnly Property CambiarClaveToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("CambiarClaveToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cambiar Idioma.
        '''</summary>
        Friend Shared ReadOnly Property CambiarIdiomaToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("CambiarIdiomaToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reportes Clientes.
        '''</summary>
        Friend Shared ReadOnly Property ClientesToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ClientesToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Criticidad Alta.
        '''</summary>
        Friend Shared ReadOnly Property CriticidadAltaToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("CriticidadAltaToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Familia - Patente.
        '''</summary>
        Friend Shared ReadOnly Property FamilaPatenteToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("FamilaPatenteToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Permisos.
        '''</summary>
        Friend Shared ReadOnly Property FamiliaToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("FamiliaToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modulo Clientes.
        '''</summary>
        Friend Shared ReadOnly Property frmcliente() As String
            Get
                Return ResourceManager.GetString("frmcliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Apellido.
        '''</summary>
        Friend Shared ReadOnly Property lblApe() As String
            Get
                Return ResourceManager.GetString("lblApe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cantidad.
        '''</summary>
        Friend Shared ReadOnly Property lblcantidad() As String
            Get
                Return ResourceManager.GetString("lblcantidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cliente.
        '''</summary>
        Friend Shared ReadOnly Property lblCliente() As String
            Get
                Return ResourceManager.GetString("lblCliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cuotas.
        '''</summary>
        Friend Shared ReadOnly Property lblCuotas() As String
            Get
                Return ResourceManager.GetString("lblCuotas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cuotas Pendientes.
        '''</summary>
        Friend Shared ReadOnly Property lblCuotasPende() As String
            Get
                Return ResourceManager.GetString("lblCuotasPende", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Descripcion.
        '''</summary>
        Friend Shared ReadOnly Property lbldesc() As String
            Get
                Return ResourceManager.GetString("lbldesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Desde.
        '''</summary>
        Friend Shared ReadOnly Property lblDesde() As String
            Get
                Return ResourceManager.GetString("lblDesde", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Direccion.
        '''</summary>
        Friend Shared ReadOnly Property lbldir() As String
            Get
                Return ResourceManager.GetString("lbldir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Dni.
        '''</summary>
        Friend Shared ReadOnly Property lblDni() As String
            Get
                Return ResourceManager.GetString("lblDni", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Editorial.
        '''</summary>
        Friend Shared ReadOnly Property lbleditorial() As String
            Get
                Return ResourceManager.GetString("lbleditorial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Email.
        '''</summary>
        Friend Shared ReadOnly Property lblemail() As String
            Get
                Return ResourceManager.GetString("lblemail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Fecha.
        '''</summary>
        Friend Shared ReadOnly Property lblfec() As String
            Get
                Return ResourceManager.GetString("lblfec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Fecha.
        '''</summary>
        Friend Shared ReadOnly Property lblFecha() As String
            Get
                Return ResourceManager.GetString("lblFecha", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Hasta.
        '''</summary>
        Friend Shared ReadOnly Property lblHasta() As String
            Get
                Return ResourceManager.GetString("lblHasta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Importe.
        '''</summary>
        Friend Shared ReadOnly Property lblImporte() As String
            Get
                Return ResourceManager.GetString("lblImporte", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Libro.
        '''</summary>
        Friend Shared ReadOnly Property lblLib() As String
            Get
                Return ResourceManager.GetString("lblLib", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Libro.
        '''</summary>
        Friend Shared ReadOnly Property lblLibro() As String
            Get
                Return ResourceManager.GetString("lblLibro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Listado Clientes.
        '''</summary>
        Friend Shared ReadOnly Property lblListadoClientes() As String
            Get
                Return ResourceManager.GetString("lblListadoClientes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nivel.
        '''</summary>
        Friend Shared ReadOnly Property lblNivel() As String
            Get
                Return ResourceManager.GetString("lblNivel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nombre.
        '''</summary>
        Friend Shared ReadOnly Property lblNom() As String
            Get
                Return ResourceManager.GetString("lblNom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Precio.
        '''</summary>
        Friend Shared ReadOnly Property lblprecio() As String
            Get
                Return ResourceManager.GetString("lblprecio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Saldo.
        '''</summary>
        Friend Shared ReadOnly Property lblsaldo() As String
            Get
                Return ResourceManager.GetString("lblsaldo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Seleccionar Criticidad.
        '''</summary>
        Friend Shared ReadOnly Property lblSeleccionarCrit() As String
            Get
                Return ResourceManager.GetString("lblSeleccionarCrit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Seleccionar Fecha.
        '''</summary>
        Friend Shared ReadOnly Property lblSeleccionarFec() As String
            Get
                Return ResourceManager.GetString("lblSeleccionarFec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Seleccionar Usuario.
        '''</summary>
        Friend Shared ReadOnly Property lblSeleccionarUsuario() As String
            Get
                Return ResourceManager.GetString("lblSeleccionarUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Telefono.
        '''</summary>
        Friend Shared ReadOnly Property lbltel() As String
            Get
                Return ResourceManager.GetString("lbltel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Alta.
        '''</summary>
        Friend Shared ReadOnly Property LblUsuario() As String
            Get
                Return ResourceManager.GetString("LblUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Vendedor.
        '''</summary>
        Friend Shared ReadOnly Property lblVendedor() As String
            Get
                Return ResourceManager.GetString("lblVendedor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modulo Clientes.
        '''</summary>
        Friend Shared ReadOnly Property ModuloClientesToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ModuloClientesToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modulo Libros.
        '''</summary>
        Friend Shared ReadOnly Property ModuloLibrosToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ModuloLibrosToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modulo Reportes.
        '''</summary>
        Friend Shared ReadOnly Property ModuloReportesToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ModuloReportesToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modulo Seguridad.
        '''</summary>
        Friend Shared ReadOnly Property ModuloSeguridadToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ModuloSeguridadToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modulo Vendedores.
        '''</summary>
        Friend Shared ReadOnly Property ModuloVendedoresToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ModuloVendedoresToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modulo Ventas.
        '''</summary>
        Friend Shared ReadOnly Property ModuloVentasToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ModuloVentasToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Recuperar Integridad.
        '''</summary>
        Friend Shared ReadOnly Property RecuperarIntegridadToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("RecuperarIntegridadToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sumatoria Saldos.
        '''</summary>
        Friend Shared ReadOnly Property SaldoSumatoriaToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("SaldoSumatoriaToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Salir.
        '''</summary>
        Friend Shared ReadOnly Property SalirToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("SalirToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Usuarios.
        '''</summary>
        Friend Shared ReadOnly Property UsuariosToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("UsuariosToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Usuarios.
        '''</summary>
        Friend Shared ReadOnly Property UsuariosToolStripMenuItem1() As String
            Get
                Return ResourceManager.GetString("UsuariosToolStripMenuItem1", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
