'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.269
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class idioma
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("UI.idioma", GetType(idioma).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Event Viewer.
        '''</summary>
        Friend Shared ReadOnly Property BitacoraToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("BitacoraToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reports Event Viewer.
        '''</summary>
        Friend Shared ReadOnly Property BitacoraToolStripMenuItem1() As String
            Get
                Return ResourceManager.GetString("BitacoraToolStripMenuItem1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Create.
        '''</summary>
        Friend Shared ReadOnly Property btnAlta() As String
            Get
                Return ResourceManager.GetString("btnAlta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Delete.
        '''</summary>
        Friend Shared ReadOnly Property btnBaja() As String
            Get
                Return ResourceManager.GetString("btnBaja", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Create.
        '''</summary>
        Friend Shared ReadOnly Property btnClieAlta() As String
            Get
                Return ResourceManager.GetString("btnClieAlta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Delete.
        '''</summary>
        Friend Shared ReadOnly Property btnCliebaja() As String
            Get
                Return ResourceManager.GetString("btnCliebaja", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a List.
        '''</summary>
        Friend Shared ReadOnly Property btnClieList() As String
            Get
                Return ResourceManager.GetString("btnClieList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modify.
        '''</summary>
        Friend Shared ReadOnly Property btnClieMod() As String
            Get
                Return ResourceManager.GetString("btnClieMod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a List.
        '''</summary>
        Friend Shared ReadOnly Property btnListar() As String
            Get
                Return ResourceManager.GetString("btnListar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a List all Events.
        '''</summary>
        Friend Shared ReadOnly Property btnListarTodos() As String
            Get
                Return ResourceManager.GetString("btnListarTodos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modify.
        '''</summary>
        Friend Shared ReadOnly Property btnModificar() As String
            Get
                Return ResourceManager.GetString("btnModificar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Change Password.
        '''</summary>
        Friend Shared ReadOnly Property CambiarClaveToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("CambiarClaveToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Change Language.
        '''</summary>
        Friend Shared ReadOnly Property CambiarIdiomaToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("CambiarIdiomaToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reports Clients.
        '''</summary>
        Friend Shared ReadOnly Property ClientesToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ClientesToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a High Critalicity.
        '''</summary>
        Friend Shared ReadOnly Property CriticidadAltaToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("CriticidadAltaToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Family - Patent.
        '''</summary>
        Friend Shared ReadOnly Property FamilaPatenteToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("FamilaPatenteToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Permissions.
        '''</summary>
        Friend Shared ReadOnly Property FamiliaToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("FamiliaToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Module Client.
        '''</summary>
        Friend Shared ReadOnly Property frmCliente() As String
            Get
                Return ResourceManager.GetString("frmCliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Last Name.
        '''</summary>
        Friend Shared ReadOnly Property lblApe() As String
            Get
                Return ResourceManager.GetString("lblApe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Amount.
        '''</summary>
        Friend Shared ReadOnly Property lblcantidad() As String
            Get
                Return ResourceManager.GetString("lblcantidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Client.
        '''</summary>
        Friend Shared ReadOnly Property lblCliente() As String
            Get
                Return ResourceManager.GetString("lblCliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Fee.
        '''</summary>
        Friend Shared ReadOnly Property lblCuotas() As String
            Get
                Return ResourceManager.GetString("lblCuotas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pending Fee.
        '''</summary>
        Friend Shared ReadOnly Property lblCuotasPende() As String
            Get
                Return ResourceManager.GetString("lblCuotasPende", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Description.
        '''</summary>
        Friend Shared ReadOnly Property lbldesc() As String
            Get
                Return ResourceManager.GetString("lbldesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a From.
        '''</summary>
        Friend Shared ReadOnly Property lblDesde() As String
            Get
                Return ResourceManager.GetString("lblDesde", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a address.
        '''</summary>
        Friend Shared ReadOnly Property lbldir() As String
            Get
                Return ResourceManager.GetString("lbldir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Dni.
        '''</summary>
        Friend Shared ReadOnly Property lblDni() As String
            Get
                Return ResourceManager.GetString("lblDni", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Editorial.
        '''</summary>
        Friend Shared ReadOnly Property lbleditorial() As String
            Get
                Return ResourceManager.GetString("lbleditorial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Email.
        '''</summary>
        Friend Shared ReadOnly Property lblemail() As String
            Get
                Return ResourceManager.GetString("lblemail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Date.
        '''</summary>
        Friend Shared ReadOnly Property lblfec() As String
            Get
                Return ResourceManager.GetString("lblfec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Date.
        '''</summary>
        Friend Shared ReadOnly Property lblFecha() As String
            Get
                Return ResourceManager.GetString("lblFecha", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a To.
        '''</summary>
        Friend Shared ReadOnly Property lblHasta() As String
            Get
                Return ResourceManager.GetString("lblHasta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Amount.
        '''</summary>
        Friend Shared ReadOnly Property lblImporte() As String
            Get
                Return ResourceManager.GetString("lblImporte", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Book.
        '''</summary>
        Friend Shared ReadOnly Property lblLib() As String
            Get
                Return ResourceManager.GetString("lblLib", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Book.
        '''</summary>
        Friend Shared ReadOnly Property lblLibro() As String
            Get
                Return ResourceManager.GetString("lblLibro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Client List.
        '''</summary>
        Friend Shared ReadOnly Property lblListadoClientes() As String
            Get
                Return ResourceManager.GetString("lblListadoClientes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Level.
        '''</summary>
        Friend Shared ReadOnly Property lblNivel() As String
            Get
                Return ResourceManager.GetString("lblNivel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a First Name.
        '''</summary>
        Friend Shared ReadOnly Property lblNom() As String
            Get
                Return ResourceManager.GetString("lblNom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Price.
        '''</summary>
        Friend Shared ReadOnly Property lblprecio() As String
            Get
                Return ResourceManager.GetString("lblprecio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Balance.
        '''</summary>
        Friend Shared ReadOnly Property lblsaldo() As String
            Get
                Return ResourceManager.GetString("lblsaldo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Select Level.
        '''</summary>
        Friend Shared ReadOnly Property lblSeleccionarCrit() As String
            Get
                Return ResourceManager.GetString("lblSeleccionarCrit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Select Date.
        '''</summary>
        Friend Shared ReadOnly Property lblSeleccionarFec() As String
            Get
                Return ResourceManager.GetString("lblSeleccionarFec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Select User.
        '''</summary>
        Friend Shared ReadOnly Property lblSeleccionarUsuario() As String
            Get
                Return ResourceManager.GetString("lblSeleccionarUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Phone.
        '''</summary>
        Friend Shared ReadOnly Property lbltel() As String
            Get
                Return ResourceManager.GetString("lbltel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a User.
        '''</summary>
        Friend Shared ReadOnly Property lblUsuario() As String
            Get
                Return ResourceManager.GetString("lblUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Seller.
        '''</summary>
        Friend Shared ReadOnly Property lblVendedor() As String
            Get
                Return ResourceManager.GetString("lblVendedor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Clients Module.
        '''</summary>
        Friend Shared ReadOnly Property ModuloClientesToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ModuloClientesToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Books Module.
        '''</summary>
        Friend Shared ReadOnly Property ModuloLibrosToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ModuloLibrosToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reports Module.
        '''</summary>
        Friend Shared ReadOnly Property ModuloReportesToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ModuloReportesToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Security Module.
        '''</summary>
        Friend Shared ReadOnly Property ModuloSeguridadToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ModuloSeguridadToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ReSales Module.
        '''</summary>
        Friend Shared ReadOnly Property ModuloVendedoresToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ModuloVendedoresToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sales Module.
        '''</summary>
        Friend Shared ReadOnly Property ModuloVentasToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("ModuloVentasToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Recover Integrity.
        '''</summary>
        Friend Shared ReadOnly Property RecuperarIntegridadToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("RecuperarIntegridadToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sum Balances.
        '''</summary>
        Friend Shared ReadOnly Property SaldoSumatoriaToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("SaldoSumatoriaToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Exit.
        '''</summary>
        Friend Shared ReadOnly Property SalirToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("SalirToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Users.
        '''</summary>
        Friend Shared ReadOnly Property UsuariosToolStripMenuItem() As String
            Get
                Return ResourceManager.GetString("UsuariosToolStripMenuItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Users.
        '''</summary>
        Friend Shared ReadOnly Property UsuariosToolStripMenuItem1() As String
            Get
                Return ResourceManager.GetString("UsuariosToolStripMenuItem1", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
