USE [master]
GO

/****** Object:  Database [Ediciones]    Script Date: 11/28/2012 00:58:11 ******/
CREATE DATABASE [Ediciones] ON  PRIMARY 
( NAME = N'EdicionesFuturo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\EdicionesFuturo.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'EdicionesFuturo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\EdicionesFuturo_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Ediciones] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Ediciones].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Ediciones] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Ediciones] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Ediciones] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Ediciones] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Ediciones] SET ARITHABORT OFF 
GO

ALTER DATABASE [Ediciones] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Ediciones] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Ediciones] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Ediciones] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Ediciones] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Ediciones] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Ediciones] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Ediciones] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Ediciones] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Ediciones] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Ediciones] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Ediciones] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Ediciones] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Ediciones] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Ediciones] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Ediciones] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Ediciones] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Ediciones] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Ediciones] SET  READ_WRITE 
GO

ALTER DATABASE [Ediciones] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Ediciones] SET  MULTI_USER 
GO

ALTER DATABASE [Ediciones] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Ediciones] SET DB_CHAINING OFF 
GO

